version: "3"

services:
  web:
    build: ./
    ports: ["5000:5000"]
    container_name: aim_flask-api
  networks:
    default:
      driver: bridge
      ipam:
        config:
          - subnet: 172.16.57.0/24